// app
export const SAGA_FETCH_ERROR_HANDLER = 'SAGA_FETCH_ERROR_HANDLER';
// company
export const COMPANY_PROFILE = 'COMPANY_PROFILE';
export const COMPANY_PROFILE_SUCCESS = 'COMPANY_PROFILE_SUCCESS';
export const COMPANY_SEARCH = 'COMPANY_SEARCH';
export const COMPANY_SEARCH_SUCCESS = 'COMPANY_SEARCH_SUCCESS';
export const OFFICER_APPOINTMENTS = 'OFFICER_APPOINTMENTS';
export const OFFICER_APPOINTMENTS_SUCCESS = 'OFFICER_APPOINTMENTS_SUCCESS';
// gecko
export const GECKO_COINS_INIT = 'GECKO_COINS_INIT';
export const GECKO_COINS_INIT_SUCCESS = 'GECKO_COINS_INIT_SUCCESS';
// login
export const LOGIN_CLICK = 'LOGIN_CLICK';
