// app
export const SAGA_FETCH_ERROR_HANDLER = 'SAGA_FETCH_ERROR_HANDLER';
// coin
export const COIN_DATA = 'COIN_DATA';
export const COIN_DATA_SUCCESS = 'COIN_DATA_SUCCESS';
export const COIN_INIT = 'COIN_INIT';
export const COIN_INIT_SUCCESS = 'COIN_INIT_SUCCESS';
export const COIN_ORDER_BOOK = 'COIN_ORDER_BOOK';
export const COIN_ORDER_BOOK_SUCCESS = 'COIN_ORDER_BOOK_SUCCESS';
// company
export const COMPANY_PROFILE = 'COMPANY_PROFILE';
export const COMPANY_PROFILE_SUCCESS = 'COMPANY_PROFILE_SUCCESS';
export const COMPANY_SEARCH = 'COMPANY_SEARCH';
export const COMPANY_SEARCH_SUCCESS = 'COMPANY_SEARCH_SUCCESS';
export const COMPANY_OFFICER_APPOINTMENTS = 'COMPANY_OFFICER_APPOINTMENTS';
export const COMPANY_OFFICER_APPOINTMENTS_SUCCESS = 'COMPANY_OFFICER_APPOINTMENTS_SUCCESS';
// login
export const LOGIN_CLICK = 'LOGIN_CLICK';
